sudo: required
services:
- docker
env:
  global:
  - PLUGIN_NAME=geoserverexplorer
  - DOCKER_VERSION=1.12.3-0~trusty
  - DOCKER_COMPOSE_VERSION=1.7.1
  # Needed for suite image which is private
  - secure: "BvupamyvdUY50+X1cmSRxPf1PvV9P+TBlEae1x9C1rNQt2wv3GAx4ep6Yy/poZI0P6PEkZNJhyk8I/4wcjNpHvgwJwcogKn+hAz3CDLipIDdNDRZDiyyId1WAh/OdNo5pna1RXga8xr13QSsBqhNcJJaCKaCc6K+AlNypEYnNTdDFpJa0LpNjjgec8vDKUyt4Qyh3tcdv8gTCY7CILXRQik7+XIZEpsuQiMjP3cksfbGYSqgoRt6Wm3/ex/DcjCbe2st38i1fshsG5RzE1xrL7UqSKPwfA4wN5ea5gS50/aPGUCn3zVQAh/JnKGG3WcBPIC3TwmjfGPHuqEy8MmpGigKuvviSOwOtfbE6oVO1xlbw3V5vlF0uAqIxSa3unkyOE1ghXVHgpYmjXH6VxYC9Gu4BvxhqAn7QwfygrA29pbuX3DLISJbhs3m4CnyGhQpPKGrhsT9Cw6UcMUFxzxlpK4A6cGngbrYRnmI1QsVhvPCSmR19Zt0Srq3NCFr0vMhfjdo31OgS9PI+LxNjFgY/4Cd0cZF65MNWDN8v4Hq2f15mAwGBWak2TuNzhwT7YmfB1rqW1glr0/L/YJ9qGTCsCBBq58B6SA9YSp5q2VFSmOhLVRn+evl03FR3dLYE3FXgozoIUA9pCdiCg72ldfGarOQ2xnqSVE/NrhMOfZBMok="
  - secure: "Ye3f6BTjKK8nz0vK4dRWdez01cxq2m6CPLKZe1SeyTWa0bbSQFTms6H8AK3fjAtQ2+vc8vpsuoACMf5Pkex8ijJsxHtHRtLV45HT1XNdzE+hxwYRJ6yJSwRhV/O5IbV/mPsTFaDl4JniFjzp1PBGv9rb7Mp0/TnGLKBbLqtfMJqGUsJkVGDAwHoAkNiQu1yL6BoK2bSIt/zvVfolvf1DcdRXHZbW9rP4IjLGOHi5okIop8GRcGnEpatrPcEnCCCuLlEZyuG9WRI1YWLOlSifPQ4w1cHxx3R5zH84LM0+8vgIEM141ZD5wLeFnmEs5KRrznp5ssP9UsIyqH+dXBSvuv4kueiHBhL+OxCHVsxZezbVNcXpmpg0llT5pLEUkdBMM6+b3tbmUcZzJV2XeUALLxZQGAf2PT0Hx5qyC/bciN5qE+v2vf1cwHm1KLTNbJIWTmOKzsyNozhSuBkdGknUjEdBUkRTUgFJbzL4RzuBcdBGOGzifsBAdJ5Fss2Uh6pZvLL6kXJJkM7V8vk0bK/Bv/8WBtYXudDpqLR3ke/s1tNNJsGGj4rJniyD5aana0Y14ZjetB0WfPdCOYFFYxnTWPTFEYxkTaz7g9c94f2G2PaOEPsJpCHmPxO2Vbdtitg1Qb0uSaF/Qc9BgOwTL1iv53ofOSxFIw6FCFSawA+YdCE="
  - secure: "qoS9Dcrl5pWqzTYm79uuwwLsBGVYeo9NtAJ0Hn46nSALuj3E5ZIjmPT9kM+3Xi/NRPsPBBA6skJ7pnE7VSKeyirKK0BVxK3BKk0dR+AIIV63an9apa6AVQgL+Qiou2rvkpHjev4SC4A4nF9a7MWjlGoDBrQkrTzItFquf+Tv1Uncdf4YRQqu3Dno4X/f4XVTXIdkN+MJ3L5BIQ04NU/gDLDKq443B1qfRAZBPY6wWfMRKIUzv5O1XQo462Cy6/dzb/B1HkqejsoQNTVQZBVGpw/Ke47RuPUiJUNhSfr8JxRzLcemWFGd2pCmMkoAQWV8hJcp93x/e8sHnuIV20piIFFCm14DBPDhgzo8iCPkZLrlURK61F9OxiLkasgAFwYTQ5GXKKLxkRV5AXDNNjHqzEDp049ARm61Wat25VPm/9iFii+HtayTdECZtxdEWI30924j9kWxd7HvAHVwfVkjpopDIRfVd51wwPSJnwSUF2pV+zVUAIGBBVFo1C6uzvKA4eeSxyCjpymADko+Fz9tJquhle3rdIqHPUhj+/CzxBO6PbmGqW+EkpoJA3AJ2y8gbVSGCWPr3k3nl3Sa+MdnA2mggsjJGe7Tii9yRBQn/tjC5XNs6Mg9+CGyt7JdrAeiNJneaY77LJrlI0PjjHpRTv7l7gVc9Ou9Z2SpaYZ8VUM="
  matrix:
  - QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master_2 PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master
before_install:
- apt-cache madison docker-engine
- sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker-compose up -d
- docker-compose ps
- sleep 10
- docker-compose exec qgis-testing-environment sh -c "qgis_setup.sh ${PLUGIN_NAME}"
- docker-compose exec qgis-testing-environment sh -c "$PIP_EXECUTABLE install paver"
script:
- docker-compose exec qgis-testing-environment sh -c "cd /tests_directory && paver setup && paver package --tests"
- docker version
- docker-compose version
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.catalogtests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.deletetests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.dragdroptests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.guitests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkicatalogtests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkideletetests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkidragdroptests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkiguitests"
- docker-compose exec qgis-testing-environment sh -c "GSHOSTNAME=boundless-test qgis_testrunner.sh geoserverexplorer.test.pkiowstests"
notifications:
  slack:
    secure: "BGVhes7seUF5U0T7PNGUxEu0MFmFVSeuF6FL+nOgtDfibX2IqWb+L7lWddJ+ZePvVYBzORTZs2vYJNQkIBPK2zDoX95rT56J+7ej6aVdxWE9dpd5BKf6IC9WBKyvSBv2gRm7J/zfSAIyKDHorY2MvemfuufDCfNoFEO0YNEKZxx3gc5A3xc3F1SCs1N8vp2DKQ0AA+Afg6G5QfEDLpW7xEYLZG/WEtS2zQIw4l/SqyszpvQEoCXblpLe1T/o6jlsuUPzZTMdaPpay2w2IyTs/IQaGUAIKThcL869Tu0TDkfFC209tRaCr2H2Fru9HCLutyX3oPgP4rwT7wI4Yg0TX47no8mBUNE3EHsh6hoKNhi8fXAzNnAZe/qDh0pFs/1yX9UTbMiq9UDa6CqHjH8dSnX8LRcs77dJlolNi9Na875y4L4VOuAqa2dScdHfjsX0WApO/t5e+RarduPfFgHZw1AkpuoW++fPmYt6geBDYyP3sX/f0z//LzIGDtrjNiIgvIlyPWnIBd++mMqLyLkjl2zr7l35JqjGDYKjzJuOPZXCHfvkmcIV7GO17HCs7P9VuyA56sycVp8iJSfYI4X26LW1l5BPVPy2muprSHyj+PnTG96vrcGM/mV2Gb1VcFaZ6RxC5jqgqnCXQ33PC7XpiKVCW80L5di0wYqH8drisnA="
after_success:
- |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
        mkdir /home/travis/.ssh/
        chmod 700 /home/travis/.ssh/
        openssl aes-256-cbc -K $encrypted_255ebb4dc86b_key -iv $encrypted_255ebb4dc86b_iv -in travis_secrets.tar.gz.enc -out travis_secrets.tar.gz -d
        tar xzvf travis_secrets.tar.gz
        mv id_rsa.qgisrepoguest /home/travis/.ssh/id_rsa.qgisrepoguest
        mv ssh_config /home/travis/.ssh/config
        chmod 600 /home/travis/.ssh/id_rsa.qgisrepoguest
        chmod 600 /home/travis/.ssh/config
        export RELEASE_ZIPNAME=${PLUGIN_NAME}.zip
        echo "Uploading ${RELEASE_ZIPNAME} to QGIS Dev..."
        scp ${PLUGIN_NAME}.zip qgisrepoguest:${UPLOADS}/${RELEASE_ZIPNAME}
        export GIT_REV=$(git rev-parse --short HEAD  | tr -d '\n')
        ssh qgisrepoguest "${UPDATER} update --dev --role desktop-qgis-plugin-dev --git-hash ${GIT_REV} ${RELEASE_ZIPNAME}"
    fi
